# Generated by Django 5.1.3 on 2024-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(help_text='Insira um JSON válido. Exemplo: {"frontend": ["React", "Vue.js"], "backend": ["Django", "Node.js"]}'),
        ),
    ]
