# Generated by Django 5.1.3 on 2024-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(help_text='Insira um JSON válido. \n        Exemplo: {\n        "frontend": ["React", "Vue.js"], \n        "backend": ["Django", "Node.js"]\n        }'),
        ),
    ]
